#                            -*- mode: org; -*-
#
#+TITLE:            OpenFOAM README for version 2.3.x
#+AUTHOR:               The OpenFOAM Foundation
#+DATE:                      22nd May 2015
#+LINK:                  http://www.openfoam.org
#+OPTIONS: author:nil ^:{}
# Copyright (c) 2014-2015 OpenFOAM Foundation.

* About OpenFOAM
  OpenFOAM is a free, open source computational fluid dynamics (CFD) software
  package released by the OpenFOAM Foundation. It has a large user base across
  most areas of engineering and science, from both commercial and academic
  organisations. OpenFOAM has an extensive range of features to solve anything
  from complex fluid flows involving chemical reactions, turbulence and heat
  transfer, to solid dynamics and electromagnetics.

* Abstract
The following new solver is proposed for OpenFOAM which is called “twoPhaseSpiceDiffusionFoam”. It is a major revised version of the solver “interFoam”. The new solver helps to simulate hydrodynamic problems for two immiscible incompressible colloid fluids that are both stratified (inhomogeneous in concentration of colloid particles).
This solver was written for a specific scientific problem – to study solutal convection in magnetic fluids undergoing first order phase transition of the “gas-liquid” type, when some colloid particles agglomerate into drops of concentrated liquid (the so called “drop-like aggregates”, that resemble drops of rain in a humid air). In some situations this drops of concentrated phase can gather together and make macroscopic hydrodynamic flows.
So, the major features of the new solver are the following:
1. Both liquids are stratified colloids with the same “chemical nature”, but with a surface tension on the phase border (this physical phenomena really takes place). The densities rho_1,  rho_2 in each point of the calculated area is a function of concentration of colloid particles. In the proposed solver a known formula was used for magnetic fluids of “magnetite - oleic acid – kerosene” type.
2. Gradient diffusion of colloid particles is allowed not only inside the stratified dilute and concentrated liquids, but also between the two phases of colloid. This process should be allowed, because it reflects the process of “vaporing” of the drop-like aggregates.
3. The viscosity dependence on concentration of particles is taken into account according to modified Chow formula.

* Copyright
  OpenFOAM is free software: you can redistribute it and/or modify it under the
  terms of the GNU General Public License as published by the Free Software
  Foundation, either version 3 of the License, or (at your option) any later
  version.  See the file =COPYING= in this directory or
  [[http://www.gnu.org/licenses/]], for a description of the GNU General Public
  License terms under which you can copy the files.

* [[http://www.OpenFOAM.org/git.php][Download and installation instructions]]
* [[http://www.OpenFOAM.org/docs][Documentation]]
* [[http://www.OpenFOAM.org/bugs][Reporting bugs in OpenFOAM]]
* [[http://www.openfoam.org/contact][Contacting the OpenFOAM Foundation]]
